### ISSUE TITLE
新增 endpoint 层

### ISSUE THREAD

**Issue by nuzar** [devYun/go-clean-architecture#1]
Hello , 刚看了你的《Golang 简洁架构实战》，感觉和我们的做法非常契合。关于 api 层的设计有一点想讨论下。

我们从 go-micro 借用了 endpoint 这个名词，把 api 层拆分成 endpoint 和 usecase 两层。enpoint 是最外层入口，负责接卸 HTTP，CLI，GRPC 等不同形式的请求，统一包装后调用 usecase 层的业务逻辑 `func(ctx, req) (resp, err)`，然后再将结果返回给 HTTP 或者 GRPC。

这样的做法更容易达到简洁架构的第三点要求：
> 独立于用户界面。UI可以很容易地改变，而不用改变系统的其他部分。例如，一个Web UI可以被替换成一个控制台UI，而不改变业务规则

**Comment by luozhiyun993** [comment]
明白，你这里是在api层里面加了一层转换，以适配不同的接入框架，这样框架变了，usecase也可以不用变。我觉得挺好的，值得借鉴！
